import React, { useState } from 'react';
import {
  ShieldCheck,
  AlertTriangle,
  AlertOctagon,
  Copy,
  Check,
  RotateCcw,
  Sparkles,
  Eye,
  Activity,
  FileText,
  BookmarkCheck,
  Mic,
  Video,
  ExternalLink,
  BookOpen,
  Volume2,
} from 'lucide-react';
import { AnalysisResult, VerdictType } from '../types';
import { ForensicFilterCanvas } from './ForensicFilterCanvas';
import { AudioWaveformPlayer } from './AudioWaveformPlayer';

interface ResultViewProps {
  result: AnalysisResult;
  onReset: () => void;
  onSaveToHistory: (result: AnalysisResult) => void;
  isSavedInHistory: boolean;
  onOpenLearn: () => void;
}

export const ResultView: React.FC<ResultViewProps> = ({
  result,
  onReset,
  onSaveToHistory,
  isSavedInHistory,
  onOpenLearn,
}) => {
  const [copied, setCopied] = useState<boolean>(false);

  const getVerdictTheme = (verdict: VerdictType) => {
    switch (verdict) {
      case 'Likely Authentic':
        return {
          title: 'Likely Authentic',
          color: '#22C55E', // Green #22C55E as mandated
          textColor: 'text-[#22C55E]',
          bgColor: 'bg-[#22C55E]/15',
          borderColor: 'border-[#22C55E]/40',
          glowShadow: 'shadow-[0_0_25px_rgba(34,197,94,0.25)]',
          icon: ShieldCheck,
          subtitle: 'Strong optical/acoustic sensor coherence. No significant synthetic manipulation or cloning signatures detected.',
        };
      case 'Suspicious':
        return {
          title: 'Suspicious',
          color: '#FFB020', // Amber #FFB020 as mandated
          textColor: 'text-[#FFB020]',
          bgColor: 'bg-[#FFB020]/15',
          borderColor: 'border-[#FFB020]/40',
          glowShadow: 'shadow-[0_0_25px_rgba(255,176,32,0.25)]',
          icon: AlertTriangle,
          subtitle: 'Inconclusive or irregular artifacts detected. Further contextual cross-referencing recommended.',
        };
      case 'Likely Manipulated':
        return {
          title: 'Likely Manipulated',
          color: '#FF3B5C', // Coral alert #FF3B5C
          textColor: 'text-[#FF3B5C]',
          bgColor: 'bg-[#FF3B5C]/15',
          borderColor: 'border-[#FF3B5C]/50',
          glowShadow: 'shadow-[0_0_30px_rgba(255,59,92,0.3)]',
          icon: AlertOctagon,
          subtitle: 'High-confidence indicators of AI generation, diffusion textures, face-swap seams, or neural voice synthesis.',
        };
    }
  };

  const theme = getVerdictTheme(result.verdict);
  const IconComponent = theme.icon;

  // Copy structured report to clipboard
  const handleCopyReport = () => {
    const report = `=====================================================
TRUTHLENS FORENSIC ANALYSIS REPORT
=====================================================
Verdict: ${result.verdict.toUpperCase()}
Confidence Score: ${result.confidence}%
Media Type: ${result.mediaType.toUpperCase()}
Timestamp: ${new Date(result.timestamp).toISOString()}
${result.videoTimestamp !== undefined ? `Video Keyframe Timestamp: ${result.videoTimestamp}s\n` : ''}
${result.claimContext ? `Evaluated Claim: "${result.claimContext}"\n` : ''}
EXECUTIVE SUMMARY:
${result.summary}

KEY FORENSIC EVIDENCE:
${result.evidence.map((e, idx) => `${idx + 1}. ${e}`).join('\n')}

TECHNICAL PILLAR RATINGS:
${
  result.mediaType === 'audio'
    ? `- Vocal Cadence: ${result.forensicBreakdown?.vocalCadenceCoherence || 'N/A'}
- Spectral Phase: ${result.forensicBreakdown?.spectralPhaseContinuity || 'N/A'}
- Breath Acoustics: ${result.forensicBreakdown?.breathAcoustics || 'N/A'}
- Neural Vocoder Artifacts: ${result.forensicBreakdown?.syntheticVocoderArtifacts || 'N/A'}`
    : `- Lighting Physics: ${result.forensicBreakdown?.lightingConsistency || 'N/A'}
- Anatomical Geometry: ${result.forensicBreakdown?.anatomicalAccuracy || 'N/A'}
- Boundary Seams: ${result.forensicBreakdown?.boundaryIntegrity || 'N/A'}
- Generative Signatures: ${result.forensicBreakdown?.generativeSignatures || 'N/A'}`
}
=====================================================
Generated by TruthLens AI Forensic Engine
=====================================================`;

    navigator.clipboard.writeText(report);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="w-full max-w-5xl mx-auto space-y-6 animate-in fade-in duration-300">
      {/* Subtle Success Pulse Ribbon ONLY if verdict is 'Likely Authentic' */}
      {result.verdict === 'Likely Authentic' && (
        <div className="p-3.5 rounded-xl bg-gradient-to-r from-emerald-500/20 via-emerald-500/10 to-transparent border border-emerald-500/40 text-emerald-400 flex items-center justify-between text-xs font-semibold shadow-[0_0_20px_rgba(34,197,94,0.15)] animate-pulse">
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-4 h-4" />
            <span>Integrity Verified: Natural biological and optical physics verified across all frequency layers.</span>
          </div>
          <span className="text-[10px] font-mono uppercase bg-emerald-500/20 px-2 py-0.5 rounded">
            AUTHENTIC
          </span>
        </div>
      )}

      {/* Top Action Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 p-3.5 rounded-xl bg-[#0A192F] border border-[#1E3A5F]">
        <button
          id="scan-another-btn"
          type="button"
          onClick={onReset}
          className="flex items-center gap-2 px-3.5 py-1.5 rounded-lg bg-[#11263F] hover:bg-[#1E3A5F] text-slate-200 border border-[#1E3A5F] text-xs font-semibold transition-all hover:scale-[1.02]"
        >
          <RotateCcw className="w-3.5 h-3.5 text-[#00D9FF]" />
          <span>Scan Another</span>
        </button>

        <div className="flex items-center gap-2">
          <button
            id="learn-cues-btn"
            type="button"
            onClick={onOpenLearn}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[#11263F] hover:bg-[#1E3A5F] text-slate-300 hover:text-white border border-[#1E3A5F] text-xs font-semibold transition-all"
          >
            <BookOpen className="w-3.5 h-3.5 text-[#00D9FF]" />
            <span>Learn About Deepfakes</span>
          </button>

          <button
            id="save-history-btn"
            type="button"
            onClick={() => onSaveToHistory(result)}
            disabled={isSavedInHistory}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all border ${
              isSavedInHistory
                ? 'bg-emerald-500/20 text-emerald-400 border-emerald-500/40 cursor-default'
                : 'bg-[#11263F] hover:bg-[#1E3A5F] text-slate-300 hover:text-white border-[#1E3A5F]'
            }`}
          >
            <BookmarkCheck className="w-3.5 h-3.5" />
            <span>{isSavedInHistory ? 'Saved in History' : 'Save to History'}</span>
          </button>

          <button
            id="copy-report-btn"
            type="button"
            onClick={handleCopyReport}
            className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-[#00D9FF]/20 hover:bg-[#00D9FF]/30 text-[#00D9FF] border border-[#00D9FF]/40 text-xs font-semibold transition-all"
          >
            {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Report Copied!' : 'Copy Report'}</span>
          </button>
        </div>
      </div>

      {/* Main Verdict & Gauge Banner */}
      <div
        id="verdict-banner"
        className={`p-6 sm:p-8 rounded-2xl bg-[#0A192F] border ${theme.borderColor} ${theme.glowShadow} relative overflow-hidden transition-all`}
      >
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-center">
          {/* Left: Verdict Badge & Headline */}
          <div className="lg:col-span-8 space-y-3">
            <div className="flex items-center gap-2 flex-wrap">
              <span
                className={`inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full text-xs font-bold uppercase tracking-wider font-mono ${theme.bgColor} ${theme.textColor} border ${theme.borderColor}`}
              >
                <IconComponent className="w-4 h-4" />
                VERDICT: {theme.title}
              </span>
              <span className="text-[11px] font-mono text-slate-400">
                SCANNED {new Date(result.timestamp).toLocaleTimeString()}
              </span>
              {result.videoTimestamp !== undefined && (
                <span className="text-[11px] font-mono px-2 py-0.5 rounded bg-[#11263F] text-[#00D9FF] border border-[#1E3A5F]">
                  KEYFRAME: {result.videoTimestamp}s
                </span>
              )}
            </div>

            <h2 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
              {result.verdict === 'Likely Manipulated'
                ? result.mediaType === 'audio'
                  ? 'Synthetic Voice Cloning / Acoustic Manipulation Detected'
                  : 'Synthetic Generation / Tampering Detected'
                : result.verdict === 'Likely Authentic'
                ? 'Authentic Sensor / Acoustic Coherence Verified'
                : 'Suspicious / Inconclusive Visual Anomalies'}
            </h2>

            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
              {theme.subtitle}
            </p>
          </div>

          {/* Right: Circular Confidence Gauge */}
          <div className="lg:col-span-4 flex flex-col items-center justify-center p-4 rounded-xl bg-[#11263F]/80 border border-[#1E3A5F]">
            <span className="text-[11px] uppercase tracking-widest font-mono text-slate-400 mb-2">
              Forensic Confidence
            </span>

            <div className="relative w-28 h-28 flex items-center justify-center">
              {/* Circular SVG Progress */}
              <svg className="w-full h-full transform -rotate-90" viewBox="0 0 100 100">
                <circle
                  cx="50"
                  cy="50"
                  r="40"
                  stroke="#1E3A5F"
                  strokeWidth="8"
                  fill="transparent"
                />
                <circle
                  cx="50"
                  cy="50"
                  r="40"
                  stroke={theme.color}
                  strokeWidth="8"
                  strokeDasharray="251.2"
                  strokeDashoffset={251.2 - (251.2 * result.confidence) / 100}
                  strokeLinecap="round"
                  fill="transparent"
                  className="transition-all duration-1000 ease-out"
                />
              </svg>

              <div className="absolute flex flex-col items-center justify-center">
                <span className="text-2xl font-black font-mono text-white leading-none">
                  {result.confidence}%
                </span>
                <span className="text-[9px] font-mono text-slate-400 uppercase mt-0.5">
                  CERTAINTY
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Mandated One-Sentence Plain-Language Summary in Italic Quote Block */}
        <div className="mt-6 p-4 rounded-xl bg-[#11263F] border border-[#1E3A5F] flex items-start gap-3">
          <div className="p-2 rounded-lg bg-[#00D9FF]/10 text-[#00D9FF] flex-shrink-0 mt-0.5">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <span className="text-[10px] uppercase font-mono tracking-wider text-[#00D9FF] font-semibold block mb-0.5">
              EXECUTIVE SUMMARY
            </span>
            <p className="text-xs sm:text-sm italic font-medium text-slate-100 leading-relaxed">
              "{result.summary}"
            </p>
          </div>
        </div>
      </div>

      {/* Two-Column Section: Media Inspector (Left) + Staggered Evidence Bullet Points (Right) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Media Inspector */}
        <div className="lg:col-span-6 space-y-4">
          <div className="p-5 rounded-2xl bg-[#0A192F] border border-[#1E3A5F] shadow-lg">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-bold text-white flex items-center gap-2">
                {result.mediaType === 'audio' ? (
                  <>
                    <Mic className="w-4 h-4 text-[#00D9FF]" />
                    Acoustic Voice Player
                  </>
                ) : (
                  <>
                    <Eye className="w-4 h-4 text-[#00D9FF]" />
                    Forensic Optical Visualizer
                  </>
                )}
              </h3>
              <span className="text-[11px] font-mono text-slate-400 uppercase">
                {result.mediaType}
              </span>
            </div>

            {/* Render Audio Waveform Player for voice, or Forensic Canvas for Visuals */}
            {result.mediaType === 'audio' ? (
              <AudioWaveformPlayer
                audioSrc={result.mediaPreview}
                fileName={result.fileName || 'Inspected Audio Clip'}
              />
            ) : (
              <ForensicFilterCanvas
                imageSrc={result.mediaPreview}
                verdictCoral={result.verdict === 'Likely Manipulated'}
              />
            )}
          </div>

          {/* Context if claim was provided */}
          {result.claimContext && (
            <div className="p-4 rounded-xl bg-[#0A192F] border border-[#1E3A5F] text-xs">
              <span className="text-[10px] font-mono uppercase text-slate-400 block mb-1">
                EVALUATED CLAIM CONTEXT:
              </span>
              <p className="text-slate-200 italic font-medium">"{result.claimContext}"</p>
            </div>
          )}
        </div>

        {/* Right Column: Key Evidence & Forensic Pillar Matrix */}
        <div className="lg:col-span-6 space-y-4">
          {/* Key Evidence Observations (With 100ms Staggered Animation) */}
          <div className="p-5 rounded-2xl bg-[#0A192F] border border-[#1E3A5F] shadow-lg">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-bold text-white flex items-center gap-2">
                <FileText className="w-4 h-4 text-[#00D9FF]" /> Key Forensic Evidence Points
              </h3>
              <span className="text-xs font-mono text-[#00D9FF] px-2 py-0.5 rounded bg-[#00D9FF]/10">
                {result.evidence.length} Findings
              </span>
            </div>

            <div className="space-y-3">
              {result.evidence.map((item, idx) => (
                <div
                  key={idx}
                  style={{ animationDelay: `${idx * 100}ms` }}
                  className="flex items-start gap-3 p-3.5 rounded-xl bg-[#11263F]/70 border border-[#1E3A5F] text-xs text-slate-200 animate-in fade-in slide-in-from-bottom-2 duration-300"
                >
                  <div className="flex items-center justify-center w-5 h-5 rounded-full bg-[#00D9FF]/20 text-[#00D9FF] font-mono text-[11px] font-bold flex-shrink-0 mt-0.5">
                    {idx + 1}
                  </div>
                  <p className="leading-relaxed">{item}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Forensic Breakdown Matrix (Visual vs Audio) */}
          {result.forensicBreakdown && (
            <div className="p-5 rounded-2xl bg-[#0A192F] border border-[#1E3A5F] shadow-lg">
              <h3 className="text-sm font-bold text-white mb-3 flex items-center gap-2">
                <Activity className="w-4 h-4 text-[#00D9FF]" />
                {result.mediaType === 'audio' ? 'Acoustic Signal Breakdown' : 'Forensic Pillar Matrix'}
              </h3>

              {result.mediaType === 'audio' ? (
                <div className="grid grid-cols-2 gap-2.5 text-xs">
                  {/* Vocal Cadence */}
                  <div className="p-2.5 rounded-lg bg-[#11263F]/60 border border-[#1E3A5F]">
                    <span className="text-[10px] text-slate-400 uppercase font-mono block">
                      Vocal Cadence & Prosody
                    </span>
                    <span
                      className={`font-semibold mt-0.5 block ${
                        result.forensicBreakdown.vocalCadenceCoherence === 'Natural Cadence'
                          ? 'text-[#22C55E]'
                          : 'text-[#FF3B5C]'
                      }`}
                    >
                      {result.forensicBreakdown.vocalCadenceCoherence || 'Analyzed'}
                    </span>
                  </div>

                  {/* Spectral Phase */}
                  <div className="p-2.5 rounded-lg bg-[#11263F]/60 border border-[#1E3A5F]">
                    <span className="text-[10px] text-slate-400 uppercase font-mono block">
                      Spectral Frequency Floor
                    </span>
                    <span
                      className={`font-semibold mt-0.5 block ${
                        result.forensicBreakdown.spectralPhaseContinuity === 'Smooth Waveform'
                          ? 'text-[#22C55E]'
                          : 'text-[#FF3B5C]'
                      }`}
                    >
                      {result.forensicBreakdown.spectralPhaseContinuity || 'Analyzed'}
                    </span>
                  </div>

                  {/* Respiration */}
                  <div className="p-2.5 rounded-lg bg-[#11263F]/60 border border-[#1E3A5F]">
                    <span className="text-[10px] text-slate-400 uppercase font-mono block">
                      Biological Respiration
                    </span>
                    <span
                      className={`font-semibold mt-0.5 block ${
                        result.forensicBreakdown.breathAcoustics === 'Authentic Respiration'
                          ? 'text-[#22C55E]'
                          : 'text-[#FF3B5C]'
                      }`}
                    >
                      {result.forensicBreakdown.breathAcoustics || 'Analyzed'}
                    </span>
                  </div>

                  {/* Vocoder Artifacts */}
                  <div className="p-2.5 rounded-lg bg-[#11263F]/60 border border-[#1E3A5F]">
                    <span className="text-[10px] text-slate-400 uppercase font-mono block">
                      Neural Vocoder Fingerprint
                    </span>
                    <span
                      className={`font-semibold mt-0.5 block ${
                        result.forensicBreakdown.syntheticVocoderArtifacts === 'None Detected'
                          ? 'text-[#22C55E]'
                          : 'text-[#FF3B5C]'
                      }`}
                    >
                      {result.forensicBreakdown.syntheticVocoderArtifacts || 'Analyzed'}
                    </span>
                  </div>
                </div>
              ) : (
                <div className="grid grid-cols-2 gap-2.5 text-xs">
                  {/* Lighting */}
                  <div className="p-2.5 rounded-lg bg-[#11263F]/60 border border-[#1E3A5F]">
                    <span className="text-[10px] text-slate-400 uppercase font-mono block">
                      Lighting Physics
                    </span>
                    <span
                      className={`font-semibold mt-0.5 block ${
                        result.forensicBreakdown.lightingConsistency === 'Consistent'
                          ? 'text-[#22C55E]'
                          : result.forensicBreakdown.lightingConsistency === 'Anomalous'
                          ? 'text-[#FF3B5C]'
                          : 'text-[#FFB020]'
                      }`}
                    >
                      {result.forensicBreakdown.lightingConsistency || 'Inconclusive'}
                    </span>
                  </div>

                  {/* Anatomy */}
                  <div className="p-2.5 rounded-lg bg-[#11263F]/60 border border-[#1E3A5F]">
                    <span className="text-[10px] text-slate-400 uppercase font-mono block">
                      Facial & Anatomy
                    </span>
                    <span
                      className={`font-semibold mt-0.5 block ${
                        result.forensicBreakdown.anatomicalAccuracy === 'Natural'
                          ? 'text-[#22C55E]'
                          : result.forensicBreakdown.anatomicalAccuracy === 'Distorted'
                          ? 'text-[#FF3B5C]'
                          : 'text-[#FFB020]'
                      }`}
                    >
                      {result.forensicBreakdown.anatomicalAccuracy || 'Inconclusive'}
                    </span>
                  </div>

                  {/* Boundaries */}
                  <div className="p-2.5 rounded-lg bg-[#11263F]/60 border border-[#1E3A5F]">
                    <span className="text-[10px] text-slate-400 uppercase font-mono block">
                      Edge Seams & Halos
                    </span>
                    <span
                      className={`font-semibold mt-0.5 block ${
                        result.forensicBreakdown.boundaryIntegrity === 'Sharp & Seamless'
                          ? 'text-[#22C55E]'
                          : result.forensicBreakdown.boundaryIntegrity === 'Blending Artifacts'
                          ? 'text-[#FF3B5C]'
                          : 'text-[#FFB020]'
                      }`}
                    >
                      {result.forensicBreakdown.boundaryIntegrity || 'Inconclusive'}
                    </span>
                  </div>

                  {/* Generative */}
                  <div className="p-2.5 rounded-lg bg-[#11263F]/60 border border-[#1E3A5F]">
                    <span className="text-[10px] text-slate-400 uppercase font-mono block">
                      Diffusion / GAN
                    </span>
                    <span
                      className={`font-semibold mt-0.5 block ${
                        result.forensicBreakdown.generativeSignatures === 'None Detected'
                          ? 'text-[#22C55E]'
                          : 'text-[#FF3B5C]'
                      }`}
                    >
                      {result.forensicBreakdown.generativeSignatures || 'Inconclusive'}
                    </span>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
